/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/robot.glb -kKmsrT 
Files: ./public/robot.glb [10.05MB] > /Users/praneethnagu/Desktop/profile/profile/robot-transformed.glb [1.32MB] (87%)
Author: komov (https://sketchfab.com/komov)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/walking-robot-bcc389f59ac747eeb7bf377c21b24d78
Title: Walking robot
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/robot-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
  )
}

useGLTF.preload('/robot-transformed.glb')
